version: 2
references:
  defaults: &defaults
    docker:
      - image: circleci/openjdk@sha256:4c6a27ac13ccba2759e42d10d448c7e31af83392db00b328d7986db11a42f64c
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
  restoreCache: &restoreCache
    keys:
      - v1-dependencies-{{ checksum "/tmp/checksum.txt" }}
      - v1-dependencies-
  saveCache: &saveCache
    paths:
      - ~/.m2
    key: v1-dependencies-{{ checksum "/tmp/checksum.txt" }}
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - run: .circleci/set_version.sh
      - run: .circleci/checksum.sh /tmp/checksum.txt
      - restore_cache:
          <<: *restoreCache
      - run: mvn -s .circleci/m2-settings.xml install
      - save_cache:
          <<: *saveCache
      - persist_to_workspace:
          root: ..
          paths:
            - repo
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: .circleci/set_version.sh
      - run: .circleci/checksum.sh /tmp/checksum.txt
      - restore_cache:
          <<: *restoreCache
      - run: mvn -s .circleci/m2-settings.xml jar:jar deploy:deploy
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test:
          context: bintray-credentials
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          context: bintray-credentials
          requires:
            - build_and_test
          filters:
            tags:
              only: /^release-(.+)$/
            branches:
              ignore: /.*/
